### ISSUE TITLE
Exposing OPENSSL_str[n]casecmp functions in 3.0

### ISSUE THREAD

**Issue by beldmit** [openssl/technical-policies#44] opened 2022-04-19 09:41 UTC
We consider https://github.com/openssl/openssl/issues/18039 as a serious regression needed to be fixed.
The proper fix requires introducing API functions OPENSSL_str[n]casecmp because case insensitive comparison is widely used in openssl itself and should be available for 3rd-party provider authors.

The question is: do we support the export of OPENSSL_str[n]casecmp as public API functions in 3.0?

```
Topic: We export OPENSSL_str[n]casecmp as public API functions in 3.0
Proposed by: Dmitry
Issue link: https://github.com/openssl/openssl/issues/18039, https://github.com/openssl/openssl/issues/18069, https://github.com/openssl/openssl/issues/18103 
Public: yes
Opened: 2022-04-19
Closed: 2022-04-20
Accepted:  yes  (for: 5, against: 2, abstained: 3, not voted: 0)

  Dmitry     [+1]
  Matt       [+1]
  Pauli      [+0]
  Tim        [-1]
  Richard    [ 0]
  Shane      [ 0]
  Tomas      [+1]
  Kurt       [-1]
  Matthias   [+1]
  Nicola     [+1]
```

**Comment by beldmit** [comment] 2022-04-19 09:42
Vote: [+1]

**Comment by t8m** [comment] 2022-04-19 09:43
@beldmit Could you please formulate this as a decision? I.E. `We export OPENSSL_str[n]casecmp as public API functions in 3.0`

**Comment by t8m** [comment] 2022-04-19 09:44
Please also look at the closed issues in this repo for examples.

**Comment by beldmit** [comment] 2022-04-19 09:51
Adjusted, thanks!

**Comment by romen** [comment] 2022-04-19 10:05
Vote: [+1]

**Comment by mattcaswell** [comment] 2022-04-19 10:30
Vote: [+1]

**Comment by mspncp** [comment] 2022-04-19 10:30
Vote: [+1]

**Comment by t8m** [comment] 2022-04-19 11:27
Vote: [+1]

**Comment by t-j-h** [comment] 2022-04-19 12:33
Vote: [-1]

**Comment by slontis** [comment] 2022-04-20 00:18
Vote: [0]

**Comment by levitte** [comment] 2022-04-20 05:48
Vote: [0]

**Comment by paulidale** [comment] 2022-04-20 07:27
Vote: [+0]

**Comment by t8m** [comment] 2022-04-20 11:06
@beldmit The vote can be closed, if you want. The remaining missing vote (@kroeckx) cannot change the outcome.

**Comment by t-j-h** [comment] 2022-04-20 11:19
I declare the vote closed (as can any OTC member). The outcome will not change with one more vote as there is clearly a strong consensus to accept adding an API in a stable release in this context.

**Comment by beldmit** [comment] 2022-04-20 11:23
Sorry, my fault. I thought we need have 6 votes to support.
Many thanks!

**Comment by kroeckx** [comment] 2022-04-23 20:58
I agree that we need a function that does an case insensitive compare in ASCII. The only reason this seems to be a public symbol is for using it in the apps. That really don't seem like a good motivation for me to have it public in a stable release, so I'm voting -1.

**Comment by romen** [comment] 2022-04-23 21:38
@kroeckx The argument in favor was that it is needed by provider authors (similarly to how we need it for our providers), despite it looking like a new feature: we are back porting it to 3.0 to fix our providers from regressions introduced by the new architecture, that could likely similarly affect external providers.

**Comment by t8m** [comment] 2022-05-10 15:38
As the vote has been closed and recorded, I am closing the issue.

**Closed by t8m** 2022-05-10 15:38 UTC
Labels: accepted

**Comment by fariborz4** [comment] 2022-05-12 01:23
Tanks
